env:
  browser: true
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "google"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: {
  "indent": ["error", 2],
  "max-len": ["error", { "code": 120 }],
  "arrow-body-style": ["error", "always"],
  "comma-dangle": ["error", "never"],
  "@typescript-eslint/no-var-requires": 0,
  "no-console": 0,
  "new-cap": ["error", { "properties": false }]
}